### ISSUE TITLE
The to-do list

### ISSUE THREAD

**Issue by rootm0s** [rootm0s/WinPwnage#19]
**The to-do list:**
- [ ] Update all the "print_" messages so they make more sense
- [ ] Update all function descriptions so they are correct
- [ ] Update readme
- [ ] A better way to display the scan results
- [x] A better way to do cleanup. Right now..  if function returns False in early stage, this prevents the cleanup in most of the functions. (Fixed in: https://github.com/rootm0s/WinPwnage/commit/f8dd0a67e868fe8e8a7fa11dd12ffac2012b2572)
- [ ] Restructure winstructures, it's all messy right now 
- [x] Convert the code to python3 but keep python2 support so Pupy (https://github.com/n1nj4sec/pupy) can work
- [x] Add automated testing (Travis CI, AppVeyor, etc.)

**Comment by cclauss** [comment]
* [ ] Add automated testing (CircleCI, Travis CI, etc.)?

**Comment by rootm0s** [comment]
> * [ ]  Add automated testing (CircleCI, Travis CI, AppVeyor, etc.)?

I do all the testing manually at the moment. I don't use any of those since there's no version-handling on this project. Is it simular to [unittest](https://docs.python.org/2/library/unittest.html)?

**Comment by cclauss** [comment]
These are automated tools that test each pull request _before_ it is reviewed.  _One_ of the tests that they could run could be unittests. They could also run other test frameworks (pytest) and linters (pylint, flake8, mypy, etc).

CPython runs several (click __show checks__):
* https://github.com/python/cpython/pull/12472#partial-pull-merging

**Comment by rootm0s** [comment]
Alright, thanks for the info. I'll add it to the todo!

**Comment by rootm0s** [comment]
Followed your steps and merged the PR @cclauss - let me know if I missed something, im new to Travis Ci.

**Comment by cclauss** [comment]
Tests are running now... #23

**Comment by rootm0s** [comment]
Merged [#23](https://github.com/rootm0s/WinPwnage/pull/23) as well

**Comment by cclauss** [comment]
Nice work!  So the rule going forward should be: If Travis is not green, the PR should not be merged.

**Comment by cclauss** [comment]
You can check the last box in the list above.

**Comment by rootm0s** [comment]
> Nice work! So the rule going forward should be: If Travis is not green, the PR should not be merged.

Alright, good to know. Thanks!

> You can check the last box in the list above.

Done!

**Comment by cclauss** [comment]
Is it time to check the second last box above?

**Comment by rootm0s** [comment]
> Is it time to check the second last box above?

It is, going too! Thanks for all the help so far. Really appreciated!

**Comment by rootm0s** [comment]
Missclick, lol.

**Comment by rootm0s** [comment]
Restructure  of winstructures is completed in PR https://github.com/rootm0s/WinPwnage/commit/5cd9c8be20bf6b17249f7297bfcde91d6ac0f7d9

**Comment by rootm0s** [comment]
Readme got updated in: https://github.com/rootm0s/WinPwnage/commit/c7d895db77ffc532c50e8bc0459e2344e7d245cb

**Comment by rootm0s** [comment]
@cclauss Is it possible for Travis-ci to ignore colorama import if it's not being used?

**Comment by rootm0s** [comment]
Added:
> * [ ]  Deprecate DLL based methods/functions

**Reason:**
Cannot support DLL based methods because I don't have the time to create proxy dll's and test existing functions and new functions. These methods are also quite messy in my opinion, payload can get stucked on disk while using UAC bypass method because the DLL is still loaded.

**Comment by psyraed** [comment]
Hi ) 

Used pyinstaller --onefile main.py to make  main.exe 

Whn i run it:  main.exe -scan

C:\Users\Usuari\Desktop\WinPwnage-master\dist>main.exe -scan

 [!] Comparing build number (18363) against 'Fixed In' build numbers

 Id:    Type:           Compatible:     Description:
 ----   ------          -----------     -------------

    
No any scan provided

Thanks for help and congrats )

**Comment by rootm0s** [comment]
> #53
> 
> Used pyinstaller --onefile main.py to make main.exe
> 
> Whn i run it: main.exe -scan
> 
> C:\Users\Usuari\Desktop\WinPwnage-master\dist>main.exe -scan
> 
> [!] Comparing build number (18363) against 'Fixed In' build numbers
> 
> Id: Type: Compatible: Description:
> 
> No any scan provided
> 
> Thanks for help and congrats )

You need to specify if  you want to search for uac/persist/elevate methods. 

`main.exe -scan uac`
`main.exe -scan persist`
`main.exe -scan elevate`

**Comment by cclauss** [comment]
It would be good if the software would display a clear warning if the user forgets to specify a search.  Or it could execute a reasonable default.

**Comment by psyraed** [comment]
> > #53
> > Used pyinstaller --onefile main.py to make main.exe
> > Whn i run it: main.exe -scan
> > C:\Users\Usuari\Desktop\WinPwnage-master\dist>main.exe -scan
> > [!] Comparing build number (18363) against 'Fixed In' build numbers
> > Id: Type: Compatible: Description:
> > No any scan provided
> > Thanks for help and congrats )
> 
> You need to specify if you want to search for uac/persist/elevate methods.
> 
> `main.exe -scan uac`
> `main.exe -scan persist`
> `main.exe -scan elevate`

Hi )
Thanks for answering
Tried whith all, ( uac , persist , elevate) but no any scan.

seems maybe soft don't find the scripts to us or similar ? 

thnx again

**Comment by rootm0s** [comment]
> It would be good if the software would display a clear warning if the user forgets to specify a search. Or it could execute a reasonable default.

Agree, would be more user friendly. Or just add it to the README, some scan arguments so people understand how it works. 

It does say it expect one more argument if only passing `--scan/-s` to `main.py`. 
```
usage: main.py [-h] [-s SCAN [SCAN ...]] [-u USE [USE ...]] [-i ID [ID ...]] [-p PAYLOAD [PAYLOAD ...]] [-r]
main.py: error: argument -s/--scan: expected at least one argument
```

**Comment by rootm0s** [comment]
> > > #53
> > > Used pyinstaller --onefile main.py to make main.exe
> > > Whn i run it: main.exe -scan
> > > C:\Users\Usuari\Desktop\WinPwnage-master\dist>main.exe -scan
> > > [!] Comparing build number (18363) against 'Fixed In' build numbers
> > > Id: Type: Compatible: Description:
> > > No any scan provided
> > > Thanks for help and congrats )
> > 
> > 
> > You need to specify if you want to search for uac/persist/elevate methods.
> > `main.exe -scan uac`
> > `main.exe -scan persist`
> > `main.exe -scan elevate`
> 
> Hi )
> Thanks for answering
> Tried whith all, ( uac , persist , elevate) but no any scan.
> 
> seems maybe soft don't find the scripts to us or similar ?
> 
> thnx again

Create a separate issue here on Github and provide what python version you run, will try to help you

**Comment by rootm0s** [comment]
> It would be good if the software would display a clear warning if the user forgets to specify a search. Or it could execute a reasonable default.

Added some examples to README for now:
https://github.com/rootm0s/WinPwnage/commit/a8ddf8465e6caec37debc4ce9be1782387ca7706
